[versions]
fabric-api = "0.136.0+1.21.10"
fabric-loader = "0.17.3"
fabric-minecraft = "1.21.10"
java = "21"
minecraft = "1.21.10"
modmenu = "16.0.0-rc.1"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
fabric-loom = "fabric-loom:1.13.3"
